### ISSUE TITLE
MVPレビュー依頼提出

### ISSUE THREAD

**Issue by yuya61ujiie** [yuya61ujiie/Portfolio#25]
## 各種情報
サービスの概要とMVPで検証する事柄：朝にPC作業や読書ができるカフェやワークスペース、カラオケをレビューするアプリです。MVP検証として、朝活を行うスポットの情報として、ユーザーのニーズを知ることです。
サービス名：MorningHub
サービスURL：https://yuya61ujiie-portfolio-bcd33720e946.herokuapp.com/

## READMEレビュー時にMVPリリース時点で実装予定だった機能
- [x] カフェ、ワークスペース、カラオケの登録機能
  - スポットのCRUD機能を実装
- [x] ユーザーによるレビュー投稿機能
  - 口コミのCRUD機能を実装
- [ ] お気に入りの場所を登録する機能
  - 未実装

## READMEレビュー時から変更した機能
- [x] ユーザー登録、ログイン機能
  - gem deviseを用いて実装
- [ ] お気に入り登録機能
  - 本リリース時に実装予定

## サービスイメージがわかるようなスクリーンショット等
[![Image from Gyazo](https://i.gyazo.com/d3f5a9a53075888291940c1462cf3a73.jpg)](https://gyazo.com/d3f5a9a53075888291940c1462cf3a73)
[![Image from Gyazo](https://i.gyazo.com/ba1c3d07f9fd94a8d2ff13f15d0cc80f.png)](https://gyazo.com/ba1c3d07f9fd94a8d2ff13f15d0cc80f)

**Comment by kenchasonakai** [comment]
機能確認が取れました。LGTMです。
引き続き本リリースに向けて開発頑張ってください。

画像の添付がないとスポット登録時に例外が発生したり、スポット削除時に例外が発生したりしていそうなので一通り触って改善していくとよいかと思います。

以下、LGTMを出した方々に共通してお伝えしている内容になります。
（Webアプリを就職活動で活用される方向けの内容になります）

===== 本リリースまでに以下の項目を実装してください =====
□ 独自ドメイン反映
    -> DNSやSSLの対応も必要になるのでアピールになり、URLを書類等に記載するときの見栄えも良くなります。
□ OGP（静的 or 動的）
    -> SNS等でシェアするときの見栄えが良くなります。Webアプリであればどんなアプリでも取り入れられるので対応しておきましょう。
□ RSpec（モデルテスト+システムテスト or モデルテスト+リクエストテスト）
    -> 開発における品質の意識や開発効率の意識の高さをアピールできます。Request Specをメインに最低限各機能に正常にアクセスできるか程度はテストで確認できるようにしておきましょう。
□ CI（GitHubActions）
    -> 実際に開発現場でも使われており、アプリ外で技術のアピールが出来るものです。RSpecと合わせて実装を行いましょう。
□ Rubocopを使ってのリファクタリング
    -> Lintチェックツールは開発現場で広く使われています。コードのLintを整えておくことはチームで開発することを意識するうえでとても大切になるので取り入れておきましょう。

他のプログラミング学習者のWebアプリと異なることをアピールするために、よりインパクトのある機能を複数盛り込むことが重要になってきます。
□ SNSログイン（Google or LINE）
    -> ほとんどのアプリに取り入れられてユーザー体験の向上や技術のアピールにつながるので取り入れましょう。
□ 検索機能のアップデート（オートコンプリート、マルチ検索等）   ※検索機能がある場合
    -> 特にオートコンプリートは検索体験の向上だけではなくJS系の技術も取り入れていることをアピール出来るので積極的に取り入れましょう。

ユーザー体験という面では以下の項目も大切です。
□ オートログイン
    -> ユーザー登録後に再度ログイン操作を行わせないことでユーザー体験を向上させられます。
□ 使い方説明がある
    -> 初めて訪れたユーザーに呈して使い方の説明があることで体験を向上させられます。
□ レスポンシブ対応
    -> いずれのデバイスでも綺麗にサービスが活用できることで体験が良くなります。
□ 利用規約・プライバシーポリシーを未ログイン状態でも確認できる
    -> 利用規約・プライバシーポリシーがあることで、ちゃんとしたサービスという印象を与えられます。
□ ローディングアニメーション（処理が重い箇所）
    -> 処理が重い箇所に何の対応も無いとユーザーが正しく操作できたのか困惑してしまいます。そうした際はローディングアニメーションを表示させることで体験が向上します。
